version: "3.9"
services:
  gofilemgr:
    image: mokusei13/gofilemgr:latest
    environment:
      USERNAME: "${FILEMGR_USERNAME}"
      PASSWORD: "${FILEMGR_PASSWORD}"
      ALLOWED_ROOTS: "${DISK1_PATH},${DISK2_PATH},${DISK3_PATH}"
    volumes:
      - ${DISK1_PATH}:${DISK1_PATH}:rw
      - ${DISK2_PATH}:${DISK2_PATH}:rw
      - ${DISK3_PATH}:${DISK3_PATH}:rw
    ports:
      - "8080:8080"
    restart: unless-stopped